import React from "react";



const columns = [
  { name: "ITEM", uid: "id", sortable: true },
  { name: "TIPO DE INSPECCIONES DE LA AERONAVE", uid: "name", sortable: true },
  { name: "REFERENCIA", uid: "role", sortable: true },
  { name: "FRECUENCIA POR HORAS, MESES Y DIAS", uid: "team" },
  { name: "ÚLTIMA INSPECCIÓN", uid: "age", sortable: true },
  { name: "PRÓXIMA INSPECCIÓN", uid: "Descripcion" },
  { name: "MARGEN", uid: "margin" },
  { name: "ESTADO", uid: "status", sortable: true },
  { name: "ACCIONES", uid: "actions" },
];

const statusOptions = [
  { name: "Programado", uid: "Programado" },
  { name: "Retrasado", uid: "Retrasado" },
  { name: "Proximo", uid: "Proximo" },
];

const data = [
  {
    pieza: "MOTOR JT8B",
    categoria: "TURBOFAN",
    estado: "Programado",
    descripcion: "Motor de aviación",
    ubicacion: "Hangar 3",
  },
  {
    pieza: "MOTOR JT8D",
    categoria: "TURBOFAN",
    estado: "Programado",
    descripcion: "Motor de aviación",
    ubicacion: "Hangar 1",
  },
  {
    pieza: "MOTOR CF6",
    categoria: "TURBOFAN",
    estado: "Proximo",
    descripcion: "Motor de aviación",
    ubicacion: "Hangar 2",
  },
  {
    pieza: "MOTOR PW4000",
    categoria: "TURBOFAN",
    estado: "Retrasado",
    descripcion: "Motor de aviación",
    ubicacion: "Hangar 3",
  },
  {
    pieza: "MOTOR JT8B",
    categoria: "TURBOFAN",
    estado: "Programado",
    descripcion: "Motor de aviación",
    ubicacion: "Hangar 3",
  },
  {
    pieza: "MOTOR JT8B",
    categoria: "TURBOFAN",
    estado: "Programado",
    descripcion: "Motor de aviación",
    ubicacion: "Hangar 3",
  },
  {
    pieza: "MOTOR JT8B",
    categoria: "TURBOFAN",
    estado: "Programado",
    descripcion: "Motor de aviación",
    ubicacion: "Hangar 3",
  },
  {
    pieza: "MOTOR JT8B",
    categoria: "TURBOFAN",
    estado: "Programado",
    descripcion: "Motor de aviación",
    ubicacion: "Hangar 3",
  },
  {
    pieza: "MOTOR JT8B",
    categoria: "TURBOFAN",
    estado: "Programado",
    descripcion: "Motor de aviación",
    ubicacion: "Hangar 3",
  },
  {
    pieza: "MOTOR JT8B",
    categoria: "TURBOFAN",
    estado: "Programado",
    descripcion: "Motor de aviación",
    ubicacion: "Hangar 3",
  },
  {
    pieza: "MOTOR JT8B",
    categoria: "TURBOFAN",
    estado: "Programado",
    descripcion: "Motor de aviación",
    ubicacion: "Hangar 3",
  },
  {
    pieza: "MOTOR JT8B",
    categoria: "TURBOFAN",
    estado: "Programado",
    descripcion: "Motor de aviación",
    ubicacion: "Hangar 3",
  },
  {
    pieza: "MOTOR JT8B",
    categoria: "TURBOFAN",
    estado: "Programado",
    descripcion: "Motor de aviación",
    ubicacion: "Hangar 3",
  },

  // Agrega más objetos según sea necesario
];

const pieces = [
  {
    id: 1,
    name: "[5101] - INSPECCIÓN DE HERRAJES DE CONEXIÓN DE LAS PALAS DEL ROTOR PRINCIPAL - ALS.",
    role: "ALS 04-20-00 (ATA 62)",
    team: "HORAS - 200:00",
    margin: "425:09",
    status: "Programado",
    age: "2400:00:00",
    Descripcion: "2600:00",
  },
  {
    id: 2,
    name: "[5102] - INSPECCIÓN INTERMEDIA INTERVALO DE 400 HRS. DE LA AERONAVE ",
    role: "ALS 04-20-01 (ATA 63)",
    team: "HORAS - 201:00",
    margin: "113",
    status: "Proximo",
    age: "2401:00:00",
    Descripcion: "2601:00",
  },
  {
    id: 3,
    name: "[5103] - INSPECCIÓN PERIODICA INTERVALO DE 800 HRS. // 36 M DE LA AERONAVE",
    role: "ALS 04-20-02 (ATA 64)",
    team: "HORAS - 202:00",
    margin: "290:53",
    status: "Retrasado",
    age: "2402:00:00",
    Descripcion: "2602:00",
  },
  {
    id: 4,
    name: "[5104] - INSPECCIÓN DE LOS EMPAQUES DE LAMINA METALICA DEL EJE IMPULSOR DEL ROTOR DE COLA-ALS",
    role: "ALS 04-20-03 (ATA 65)",
    team: "HORAS - 203:00",
    margin: "231",
    status: "Programado",
    age: "2403:00:00",
    Descripcion: "2603:00",
  },
  {
    id: 5,
    name: "[5105] - INSPECCIÓN DEL TUBO DE LA VARILLA DEL CONTROL VERTICAL - ALS",
    role: "ALS 04-20-04 (ATA 66)",
    team: "HORAS - 204:00",
    margin: "234",
    status: "Proximo",
    age: "2404:00:00",
    Descripcion: "2604:00",
  },
  {
    id: 6,
    name: "[5106] - INSPECCIÓN DE LA CABEZA DE LAS VARILLAS DEL ROTOR PRINCIPAL - ALS",
    role: "ALS 04-20-05 (ATA 67)",
    team: "HORAS - 205:00",
    margin: "597",
    status: "Retrasado",
    age: "2405:00:00",
    Descripcion: "2605:00",
  },
  {
    id: 7,
    name: "[5107] - INSPECCIÓN INTERVALO DE 12 MESES DE LA AERONAVE",
    role: "ALS 04-20-06 (ATA 68)",
    team: "HORAS - 206:00",
    margin: "598",
    status: "Programado",
    age: "2406:00:00",
    Descripcion: "2606:00",
  },
  {
    id: 8,
    name: "[5108] - INSPECCIÓN DE LA BATERIA DE LA AERONAVE",
    role: "ALS 04-20-07 (ATA 69)",
    team: "HORAS - 207:00",
    margin: "600",
    status: "Proximo",
    age: "2407:00:00",
    Descripcion: "2607:00",
  },
  {
    id: 9,
    name: "[5109] - INSPECCIÓN SUPLEMENTARIA DE 100 HRS. DE LA AERONAVE",
    role: "ALS 04-20-08 (ATA 70)",
    team: "HORAS - 208:00",
    margin: "590",
    status: "Retrasado",
    age: "2408:00:00",
    Descripcion: "2608:00",
  },
  {
    id: 10,
    name: "[5110] - INSPECCIÓN DEL CONJUNTO DE IBF",
    role: "ALS 04-20-09 (ATA 71)",
    team: "HORAS - 209:00",
    margin: "592",
    status: "Programado",
    age: "2409:00:00",
    Descripcion: "2609:00",
  },
  {
    id: 11,
    name: "[5111] - INSPECCIÓN DE LOS CARENADOS DEL MOTOR",
    role: "ALS 04-20-10 (ATA 72)",
    team: "HORAS - 210:00",
    margin: "594",
    status: "Proximo",
    age: "2410:00:00",
    Descripcion: "2610:00",
  },
  {
    id: 12,
    name: "[5112] - INSPECCIÓN DE LAS LINEAS HIDRAULICAS DE LA AERONAVE",
    role: "ALS 04-20-11 (ATA 73)",
    team: "HORAS - 211:00",
    margin: "501",
    status: "Retrasado",
    age: "2411:00:00",
    Descripcion: "2611:00",
  },
  {
    id: 13,
    name: "[5113] - INSPECCION BRUSH WEAR ON BLOWER BRUSH",
    role: "ALS 04-20-12 (ATA 74)",
    team: "HORAS - 212:00",
    margin: "75",
    status: "Programado",
    age: "2412:00:00",
    Descripcion: "2612:00",
  },
  {
    id: 14,
    name: "[5114] - CAMBIO DE ACEITE DE LA XMSN PRINCIPAL..",
    role: "ALS 04-20-13 (ATA 75)",
    team: "HORAS - 213:00",
    margin: "671",
    status: "Proximo",
    age: "2413:00:00",
    Descripcion: "2613:00",
  },
];

export { columns, pieces, statusOptions, data };
